
export const DEFAULT_TEXT = `Deep work is not just a skill but a superpower in the 21st century that allows you to master hard things quickly. The ability to perform deep work is becoming increasingly rare at exactly the same time it is becoming increasingly valuable in our economy. As a result, the few who cultivate this skill, and then make it the core of their working life, will thrive.`

export const SPEED_LIMIT_WPM = 650
export const MIN_WORDS_FOR_SPEED_CHECK = 3
export const MAX_CHAR_LIMIT = 20000

export const PRESETS: Record<string, string> = {
  'dopamine-loop': `The dopamine loop is a self-perpetuating cycle of craving and reward that drives addictive behaviors, particularly in the context of social media and digital consumption. When we scroll through our feeds, our brains release dopamine in anticipation of a reward—a like, a comment, or an interesting piece of content. This release creates a pleasurable sensation that reinforces the behavior, making us want to repeat it. Over time, the brain adapts to these high levels of dopamine, requiring more stimulation to achieve the same effect, which leads to compulsive scrolling and a reduced ability to focus on less stimulating tasks. Understanding this mechanism is the first step towards breaking free from the cycle and reclaiming control over our attention.`,
  'attention-residue': `Attention residue is a concept introduced by Sophie Leroy, which describes the cognitive cost of switching tasks. When you shift your focus from one task to another, a "residue" of your attention remains stuck on the original task. This residue occupies mental resources, reducing your cognitive capacity available for the new task. Even quick checks of email or social media can create this residue, leading to a significant drop in performance and IQ. To minimize attention residue, it is essential to work in long, uninterrupted blocks of time and to fully complete one task before moving on to the next.`,
  'deep-work': `Deep work refers to professional activities performed in a state of distraction-free concentration that push your cognitive capabilities to their limit. These efforts create new value, improve your skill, and are hard to replicate. In contrast, shallow work consists of non-cognitively demanding, logistical-style tasks, often performed while distracted. The ability to perform deep work is becoming increasingly rare at exactly the same time it is becoming increasingly valuable in our economy. Cultivating this skill requires disciplined practice, environmental control, and a commitment to prioritizing high-impact work over busy work.`,
  'cognitive-load': `Cognitive load theory suggests that the human brain has a limited amount of working memory resources. When learning or performing a task, these resources are used to process information. If the amount of information exceeds the brain's capacity, cognitive overload occurs, leading to errors, frustration, and reduced learning. There are three types of cognitive load: intrinsic (difficulty of the material), extraneous (how the material is presented), and germane (processing for learning). Effective design and work habits aim to minimize extraneous load and manage intrinsic load to maximize germane load, thereby optimizing performance and comprehension.`,
}
