/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ZenTypeRouteImport } from './routes/zen-type'
import { Route as VocalGymRouteImport } from './routes/vocal-gym'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as InitRouteImport } from './routes/init'
import { Route as FocusReaderRouteImport } from './routes/focus-reader'
import { Route as IndexRouteImport } from './routes/index'

const ZenTypeRoute = ZenTypeRouteImport.update({
  id: '/zen-type',
  path: '/zen-type',
  getParentRoute: () => rootRouteImport,
} as any)
const VocalGymRoute = VocalGymRouteImport.update({
  id: '/vocal-gym',
  path: '/vocal-gym',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const InitRoute = InitRouteImport.update({
  id: '/init',
  path: '/init',
  getParentRoute: () => rootRouteImport,
} as any)
const FocusReaderRoute = FocusReaderRouteImport.update({
  id: '/focus-reader',
  path: '/focus-reader',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/focus-reader': typeof FocusReaderRoute
  '/init': typeof InitRoute
  '/settings': typeof SettingsRoute
  '/vocal-gym': typeof VocalGymRoute
  '/zen-type': typeof ZenTypeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/focus-reader': typeof FocusReaderRoute
  '/init': typeof InitRoute
  '/settings': typeof SettingsRoute
  '/vocal-gym': typeof VocalGymRoute
  '/zen-type': typeof ZenTypeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/focus-reader': typeof FocusReaderRoute
  '/init': typeof InitRoute
  '/settings': typeof SettingsRoute
  '/vocal-gym': typeof VocalGymRoute
  '/zen-type': typeof ZenTypeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/focus-reader'
    | '/init'
    | '/settings'
    | '/vocal-gym'
    | '/zen-type'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/focus-reader' | '/init' | '/settings' | '/vocal-gym' | '/zen-type'
  id:
    | '__root__'
    | '/'
    | '/focus-reader'
    | '/init'
    | '/settings'
    | '/vocal-gym'
    | '/zen-type'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FocusReaderRoute: typeof FocusReaderRoute
  InitRoute: typeof InitRoute
  SettingsRoute: typeof SettingsRoute
  VocalGymRoute: typeof VocalGymRoute
  ZenTypeRoute: typeof ZenTypeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/zen-type': {
      id: '/zen-type'
      path: '/zen-type'
      fullPath: '/zen-type'
      preLoaderRoute: typeof ZenTypeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vocal-gym': {
      id: '/vocal-gym'
      path: '/vocal-gym'
      fullPath: '/vocal-gym'
      preLoaderRoute: typeof VocalGymRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/init': {
      id: '/init'
      path: '/init'
      fullPath: '/init'
      preLoaderRoute: typeof InitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/focus-reader': {
      id: '/focus-reader'
      path: '/focus-reader'
      fullPath: '/focus-reader'
      preLoaderRoute: typeof FocusReaderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FocusReaderRoute: FocusReaderRoute,
  InitRoute: InitRoute,
  SettingsRoute: SettingsRoute,
  VocalGymRoute: VocalGymRoute,
  ZenTypeRoute: ZenTypeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
